services:
  # Spring Boot Backend Service
  - type: web
    name: hydratemate-backend
    runtime: java
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -Dserver.port=$PORT -jar build/libs/Backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: Hydration-DB
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: Hydration-DB
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: Hydration-DB
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
